- id: '1767634107924'
  alias: Office – light on when presence detected
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.sonoff_snzb_06p_human_presence_sensor
      to: 'on'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      target:
        entity_id: light.office_light
  mode: single

- id: '1767634170521'
  alias: Office – light off after no presence
  trigger:
    - platform: state
      entity_id: binary_sensor.sonoff_snzb_06p_human_presence_sensor
      to: 'off'
      for:
        minutes: 3
  action:
    - service: light.turn_off
      target:
        entity_id: light.office_light
  mode: restart

- id: '1767638671704'
  alias: I'm working
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.office_work_mode
      from: 'off'
      to: 'on'
  condition: []
  action:
    - type: turn_on
      device_id: 100a058eb22ad57cc71feb0621b1c36a
      entity_id: febc2683adf55183cce427bd728b9c0f
      domain: light
  mode: single

- id: '1767638744550'
  alias: I'm done working
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.office_work_mode
      from: 'on'
      to: 'off'
  condition: []
  action:
    - type: turn_off
      device_id: 100a058eb22ad57cc71feb0621b1c36a
      entity_id: febc2683adf55183cce427bd728b9c0f
      domain: light
  mode: single

- id: '1769154628859'
  alias: Bathroom - Motion lights (variable off time)
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_occupancy
      to: 'on'
  action:
    - service: light.turn_on
      target:
        entity_id: light.bathroom_light

    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.bathroom_motion_sensor_occupancy
          to: 'off'

    - choose:
        - conditions:
            - condition: time
              after: '00:00:00'
              before: '07:00:00'
          sequence:
            - delay: '00:00:45'
      default:
        - delay: '00:02:00'

    - condition: state
      entity_id: binary_sensor.bathroom_motion_sensor_occupancy
      state: 'off'

    - service: light.turn_off
      target:
        entity_id: light.bathroom_light
  mode: restart

- id: '1769361910440'
  alias: Living Room – Chill Mode On
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.chill_mode
      to: 'on'
  action:
    - service: light.turn_on
      target:
        entity_id: 
          - light.living_room_floor_light
          - light.table_light

    - service: light.turn_off
      target:
        entity_id:
          - light.living_room_light
          - light.living_room_atrium_light
          - light.kitchen_light
  mode: single

- id: '1769363634915'
  alias: Kitchen - Cook Mode On
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.cook_mode
      to: 'on'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.adaptive_lighting_kitchen

    - service: light.turn_on
      target:
        entity_id: light.kitchen_light
      data:
        brightness_pct: 100
        kelvin: 3000
  mode: single

- id: '1769363678083'
  alias: Kitchen - Cook Mode Off
  trigger:
    - platform: state
      entity_id: input_boolean.cook_mode
      to: 'off'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.adaptive_lighting_kitchen

    - service: adaptive_lighting.apply
      target:
        entity_id: switch.adaptive_lighting_kitchen
  mode: single

- id: '1769363823883'
  alias: Chill Mode cancels cook mode
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.chill_mode
      to: 'on'
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.cook_mode
  mode: single

- id: evening_bedroom_living_floor_on
  alias: Evening – Bedroom & Living Floor On at Sunset
  trigger:
    - platform: sun
      event: sunset
  condition: []
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.living_room_floor_light
          - light.bedroom_floor_light
          - light.table_light
  mode: single

- id: kitchen_light_on_when_presence_detected
  alias: Kitchen – light on when presence detected
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_presence_sensor
      to: 'on'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen_light
  mode: single

- id: kitchen_light_off_after_no_presence
  alias: Kitchen – light off after no presence
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_presence_sensor
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: input_boolean.cook_mode
      state: 'off'
  action:
    - service: light.turn_off
      target:
        entity_id: light.kitchen_light
  mode: restart

- id: guest_bathroom_motion_lights_variable_off_time
  alias: Guest Bathroom - Motion lights (variable off time)
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bathroom_motion_sensor_occupancy
      to: 'on'
  action:
    - service: light.turn_on
      target:
        entity_id: light.guest_bathroom_light

    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.guest_bathroom_motion_sensor_occupancy
          to: 'off'

    - choose:
        - conditions:
            - condition: time
              after: '00:00:00'
              before: '07:00:00'
          sequence:
            - delay: '00:05:00'
      default:
        - delay: '00:07:00'

    - condition: state
      entity_id: binary_sensor.guest_bathroom_motion_sensor_occupancy
      state: 'off'

    - service: light.turn_off
      target:
        entity_id: light.guest_bathroom_light
  mode: restart